name: "Version"

on:
  push:
    branches:
      - main
      - test-changelog

jobs:
  version:
    name: release
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, '[TEST]')"
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          token: ${{secrets.GH_PERSONAL_ACCESS_TOKEN}}
      - run: git config --global user.name 'Github CI'
      - run: git config --global user.email 'simon.buttazzi@gmail.com'
      - run: npm install -g auto-changelog
      - run: npm config set git-tag-version true
      - run: npm version patch -m '[TEST] %s'
      - run: git push
#      - run: git push --tags