name: "Version"

on:
  push:
    branches:
      - main

jobs:
  version:
    name: release
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, '[RELEASE]')"
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          token: ${{secrets.GH_PERSONAL_ACCESS_TOKEN}}
      - run: git config --global user.name 'Github CI'
      - run: git config --global user.email 'simon.buttazzi@gmail.com'
      - run: npm version patch -m '[RELEASE] %s'
      - run: git push